controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-scheme: "${scheme}"
      service.beta.kubernetes.io/aws-load-balancer-internal: "${internal}"
      service.beta.kubernetes.io/aws-load-balancer-target-node-labels: kubernetes.io/os=linux
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"